	extrn __mods
; decrementing counter promoted to C
	ld c,(ix-2) ; peep: byte_loop_counter_to_reg_c
LCDEC:
	dec c ; peep: byte_loop_counter_to_reg_c
	ld (ix-2),c
	ret z ; peep: cond_jp_to_cond_ret
	ld e,c
	ld d,0
	call __mods
	jp LCDEC
; incrementing counter promoted to E because BC is live
	ld e,1 ; peep: byte_for_counter_to_reg_e
LEINC:
	ld b,a
	ld l,e
	ld h,0
	inc e ; peep: byte_for_counter_to_reg_e
	ld a,e
	cp 5
	jr c,LEINC ; peep: jp_to_jr
	ld (ix-4),e
	end
